spring:
  application:
    name: API-GATEWAY

#server port
server:
  port: 9090


#actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

#eureka client registration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    org.springframework.cloud.gateway.filter: DEBUG
